name: swin_unetr
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - aniso8601=9.0.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=5.0.1=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=2.2.0=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.12.0=py37h540881e_0
  - dask-core=2022.2.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.3=py37hd23a5d3_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - eigen=3.4.0=h4bd325d_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.5.0=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_105
  - flask=1.1.4=pyhd8ed1ab_0
  - flask-restx=0.5.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=hc2a2eb6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.38.0=py37h540881e_0
  - freetype=2.12.1=hca18f0e_0
  - fsspec=2022.10.0=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.74.1=h6239696_0
  - glib-tools=2.74.1=h6239696_0
  - gst-plugins-base=1.21.1=h3e40eee_1
  - gstreamer=1.21.1=hd4edc92_1
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=70.1=h27087fc_0
  - imagecodecs-lite=2019.12.3=py37hc105733_5
  - imageio=2.22.0=pyhfa7a67d_0
  - ipykernel=6.9.2=py37h25bab4e_0
  - ipython=7.32.0=py37h89c1867_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.7.0=pyhd8ed1ab_0
  - itsdangerous=1.1.0=py_0
  - jack=1.9.21=he978b8e_1
  - jedi=0.18.1=pyhd8ed1ab_2
  - jinja2=2.11.3=pyhd8ed1ab_2
  - jpeg=9e=h166bdaf_2
  - jsonschema=2.6.0=py37_1002
  - jupyter=1.0.0=py37h89c1867_7
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.3=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py37h89c1867_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py37h7cecad7_0
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.39=hc81fddc_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcap=2.66=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=15.0.3=default_h2e3cab8_0
  - libclang13=15.0.3=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libcurl=7.86.0=h7bff187_1
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.2=h27087fc_0
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libglib=2.74.1=h7a41b64_0
  - libgomp=12.2.0=h65d4601_19
  - libiconv=1.17=h166bdaf_0
  - libitk=5.2.1=hcedbc38_6
  - libitk-devel=5.2.1=h0a2745d_6
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm15=15.0.3=h63197d8_1
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=hd77ab85_1
  - libsndfile=1.1.0=h27087fc_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.4=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtiff=4.4.0=h55922b4_4
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=252=h166bdaf_0
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.10.3=h7463322_0
  - libzlib=1.2.13=h166bdaf_4
  - locket=1.0.0=pyhd8ed1ab_0
  - markupsafe=1.1.1=py37h540881e_4
  - matplotlib=3.5.3=py37h89c1867_2
  - matplotlib-base=3.5.3=py37hf395dca_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=0.8.4=py37h5e8e339_1005
  - mpg123=1.30.2=h27087fc_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.31=haf5c9bc_0
  - mysql-libs=8.0.31=h28c427c_0
  - nbconvert=5.6.1=pyhd8ed1ab_2
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - notebook=5.7.11=py37h89c1867_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.21.6=py37h976b520_0
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1s=h166bdaf_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - partd=1.3.0=pyhd8ed1ab_0
  - pcre2=10.37=hc3806b6_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py37h850a105_2
  - pip=22.3=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prometheus_client=0.15.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.27=pyha770c72_0
  - prompt_toolkit=3.0.27=hd8ed1ab_0
  - psutil=5.9.3=py37h540881e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h0d2025b_11
  - pydicom=2.3.0=pyh6c4a22f_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pynrrd=0.4.2=pyh95af2a2_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py37hf30b843_0
  - pyqt5-sip=12.11.0=py37hd23a5d3_0
  - python=3.7.12=hb7a2778_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2022.6=pyhd8ed1ab_0
  - pywavelets=1.3.0=py37hda87dfa_1
  - pyyaml=6.0=py37h540881e_4
  - pyzmq=24.0.1=py37h0c0c2a8_0
  - qt-main=5.15.6=hd477bba_1
  - qtconsole=5.4.0=pyhd8ed1ab_0
  - qtconsole-base=5.4.0=pyha770c72_0
  - qtpy=2.2.1=pyhd8ed1ab_0
  - readline=8.1.2=h0f457ee_0
  - scikit-image=0.19.3=py37hfb7772e_1
  - scipy=1.7.3=py37hf2a6cf1_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - simplegeneric=0.8.1=py_1
  - simpleitk=2.1.1.1=py37h78a9f20_0
  - sip=6.6.2=py37hd23a5d3_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.4=h4ff8645_0
  - tbb=2021.6.0=h924138e_1
  - tbb-devel=2021.6.0=h924138e_1
  - terminado=0.17.0=pyh41d4057_0
  - testpath=0.6.0=pyhd8ed1ab_0
  - tifffile=2020.6.3=py_0
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - toolz=0.12.0=pyhd8ed1ab_0
  - tornado=6.2=py37h540881e_0
  - traitlets=5.5.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - unicodedata2=14.0.0=py37h540881e_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.6.1=pyha770c72_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=h6239696_4
  - pip:
    - einops==0.5.0
    - monai-weekly==1.1.dev2244
    - nibabel==4.0.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - torch==1.13.0
    - tqdm==4.64.1
prefix: /home/natitov/miniforge/envs/swin_unetr
